apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:lAeORKU2s0P5fAAUTt+0U8MjOh+9gJ6/z0EqRs02N/KjqoHbX7FyXA==,iv:320cTJshyEqBrQPM8XxMBCzTY+TclHRNz51hfYPdsq0=,tag:MeHVjfqgsAMqtBBhyHQykQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOS91cGhFUzQrQ3FVRXpn
            KzdaVGtTVGdCbU80c0J5ckM5YTRtQnAyRGhRClNxb1hFK1FJVE9rWEgwYjUrbEpk
            bFU2SkcvcVl0dWxGemU0UjVLdXZxQ3MKLS0tIGFmRXhQUUZLaUFQZWgvN00zaVRv
            elV6RmdNZWl0bE5aSXdxRXpGYTNyeG8Ky4D6m5uf4yG6FuQkOANmVm34mI007Ldv
            0PLMwX6spyZlnDx5uxe0itNZvxBVHOPG3fJThAthTxu3dPTwjZyZfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-11T20:36:18Z"
    mac: ENC[AES256_GCM,data:V/gRvzGqqU9YYztw/IFz41R+qQv77DAMmQ2rB8kZAuP6P6ITDmsHI7rMq/YUUvxhoelyaoW08nLFN5TGRTF4sHmJGA3lsQ/LZuK2uvzwY+mLJ4RZ4TIUtmcTO4kzY4av9pdrThke4fa8ViHQtWvoRGhXgX9an7dKHEelb+pvhvM=,iv:tTuTaqf8E2NAS1uwBPscYEZGaujbDG72aU2EIwW+/Ko=,tag:DWoGfmuR8AeSzFwi7KUAeA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
