apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:L0jgelUlAvtTsgIQFF7ydq0XTJrTm+RD2KnwZofdCBm3o3EiKdaxhg==,iv:be2wg/QTZQQKARFMV7lNs3YgNmAecm9SochfZzvErOY=,tag:TEGtP1x/9kfF6QXyl0iZAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQUFhMkRPbTR3THR0WkNh
            TEJSd29XelhaZzVMc0ZoQzRmTHRnTzJ6VDBNCkN3c1M0QTNEbllEbGFwai85c3RE
            MVBIejZWL1A0UnRhWXRFSzNRSG1VRGcKLS0tIEhSMW9OaEh5MzhmcVYra3I3UWIz
            dTFZeHhycEZmUUZmQ1B3WTZhUEFVYWMKl5X/zkwuTdAs3FOXiFNbM07IuL3bJbu1
            w6A/ywcXpCwUOZbkpMMnXg6wPjKdeTOOeQrRgIfBE/C+F2OHOAYWsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-11T12:23:54Z"
    mac: ENC[AES256_GCM,data:LREAJYiCmAvuYbEZ822ZTHYab8lPej4vxht8K/yrNzbaZfC+xnJfzdmzXs/47Ksr+vU/pW+vWr03SSsKFSKDpWrpBmKKb7s9gVfNOIVL6uNDjdshjnwGwL26dVJLTIOrmFZ2ca5WhTNJf8cTkrlcz65/NWNZmFM1pYeh1dwHiyY=,iv:1+LqPiDEYjg6t7LJxI0af9I9xiGwIkznrsc9H61cWw0=,tag:DV6vtoA2bf265Bpmvnljdg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
