apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:adrsV+Rhs+6RftIgHOIiFq5/H8z+JhlgJ9NnGSTs7YDsd++/iQP0NA==,iv:LLTrXErw1KkwMmLaMgPjWzNFufjo+Mh/dB3PLTEH1N4=,tag:IxUusit9a9Do+v4Yrod6Lw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUWxnTDFjd2pXYlpLbEI2
            OWtQRE03Z3pkWDN5QklNbFpqTkxJOUx4dEY0CjlHYXFhdTcvMWJscUU0TGd2SFBU
            ZldmWFljNFA4S2tRRkpwdWpERFpoUGcKLS0tIEZlelVVVFZxbmp4S0RHcEtUUXdO
            U3ZaSVFXamluWm9mdVc3L2dPbnlxaTgKKbL25Uhag8TLwLBM/pb5wA4//EE5V7mF
            wd/XrPEX8jeAdnZynwlu96L2ilbQlU4fkxibpBih/WGoPf43+Cdwnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T17:12:45Z"
    mac: ENC[AES256_GCM,data:Kqgjw0fuN6liFGxPWK9EmAEK8vUDyWuTVE1kRR6u+fqJgUC9CDuYGJWYfHgPOMRfSEyu8zi9MF/h6aVEqRYV8xtKK1hgOi9dKy/RHDeBiJS0g3fh719qX2IRPKAyFIWkx/LhS8+VLjRponcEhKZcAmsP37ZnY0k/5DA5jZrf97M=,iv:KWFotUeEUOXc0tsaai67XuoU6h6J+3Jg/koPy4kLxa8=,tag:7Axuii9MGBNrFwMCNt+YdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
