---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  values:
    credentials:
      minio:
        type: s3
        url: "http://${S3_URL}"
        bucket: "${S3_BUCKET}-APP"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"
      blaze:
        type: s3
        url: "https://${S3_BLAZE_URL}"
        bucket: "${S3_BLAZE_BUCKET}"
        accessKey: "${S3_BLAZE_ACCESKEY}"
        secretKey: "${S3_BLAZE_SECRETKEY}"
        encrKey: "${S3_BLAZE_ENCRKEY}"
      garage:
        type: s3
        url: "http://${S3_GARAGE_URL}"
        bucket: "${S3_GARAGE_BUCKET}-APP"
        accessKey: "${S3_GARAGE_ACCESKEY}"
        secretKey: "${S3_GARAGE_SECRETKEY}"
        encrKey: "${S3_GARAGE_ENCRKEY}"
      rustfs:
        type: s3
        url: "http://${S3_RUSTFS_URL}"
        bucket: "${S3_RUSTFS_BUCKET}-APP"
        accessKey: "${S3_RUSTFS_ACCESKEY}"
        secretKey: "${S3_RUSTFS_SECRETKEY}"
        encrKey: "${S3_RUSTFS_ENCRKEY}"        