---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: not-used
spec:
  values:
    credentials:
      minio:
        type: s3
        url: "http://${S3_URL}"
        bucket: "${S3_BUCKET}-APP"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"
      blaze:
        type: s3
        url: "https://${S3_BLAZE_URL}"
        bucket: "${S3_BLAZE_BUCKET}"
        accessKey: "${S3_BLAZE_ACCESKEY}"
        secretKey: "${S3_BLAZE_SECRETKEY}"
        encrKey: "${S3_BLAZE_ENCRKEY}"
