apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:C+pfZQikYVca7LUYgrG37STinpCaxlQMfanBnomJzEP55Ou+NmyHIeq0x6VhjYDYr/i+8/05Pg/3S0ZBAaGh9gxOFI2uj1IWqhM8NfQB1RRNh3JJN1zl6plSy7lvYvcib9PnhV6Q5Ks0vzkt5RH5elWlTr53T5blr67K0B1s9Js9+h8D+w4+KcfmwJHqQs/zWZnjuVxGLn7f2OKSOB1J4wlt8jjNXHidojOi6VE7waJcc/bVYhuMvh6WZqPCU93Nsw6b0oNynu+Y39igwKUuIfFPFyrIFHvLS57kJ5UZZZIjt34hwYTkgsgloifj5FmMKxMaISXwgqYDgDXC2MY5AaKLXEMrPLQ1bQqjLq9rQbn2fsdwbMUKUSzT5S+P+fzK,iv:nL+xCkh+rzjnMNPLEYBsHD6zvqJhK+SRbZaq436mZcI=,tag:KE1Ra0DBFKKVGLDvhhIOsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:30HjdYP44SpJ0i1ya6AqlliMLSwYIrNkzjnZkCh/Gt7tANFHnQusM9kgku2CzbEJXaHXe29KEOjJ1eExKPgNPVWBEBxtwyXAYLXyAlxOh0tA6eImypGilWBtUX8+JCiiWc5g69/lFouk7jeZoUmb9MnI8Eg2KEfeiyXMF1comS5PwBzzdt3mNRzNFNLe70NEIpTBWgqgub33qtPo92SLstLsbf4ldg6SwAOkdwE9I4gpH60oO0BP8T87cFX5DeD1UM4DXxDC0PzFEjPbow==,iv:PyGehx8dk9rmo2IpvcudSfP8FEFd7cXalqeFR2uBC9E=,tag:5X+Eh5l26SwpGsRmaBHYTg==,type:str]
    known_hosts: ENC[AES256_GCM,data:63l2xNstwZremZuQ5D181kBnSRoR9PpFMJuFXu3iFFVfmC0HJPrlvt7jsCJhwkzg49pKQBmODLIgDgSSG4JS1nl6qlq+fDHEYbyUKxgUaPFGMc/7lA05xflCFoXHjNAVAML3gUinCuaLVo7KcMCpPnvrXObMAgrD3iuWWsTDAAN5rpSbGemBK1j6n8Ar9B2osTmrQmsOheQBlh6Tyi/OoeFOa2nBEAuqceCa,iv:KqmVmnFJQRR2Wbr+2A3GutOg1/LSCtiAIt67rdZEYcY=,tag:J5Ce0/dZGqQFT8YVmfeRXA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSVdiUXRkZC9razhtREll
            bFl6NkVSeWdpY1hvdkpXQy9KRjh5cTh6OGtNCkdGMStmSWYwUkpnYUtKa0Q2YThZ
            Vm9jdXQ0YzlJM2pwZUNKWWhuUUFoK1UKLS0tIFhVa0tWWXFCYW9vZGpuOWhlMUJL
            d0RJRGdmQXZFQnowN2o2N0Z0Z0lKM2sKQekwk35/u/uoyI+iKP8YYu2I86ibH/ZO
            HJ7aykSE12cSwhQvuUUUebcLvZow+rGY7IYyVMimC2GmGDmljHZzIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-04T20:14:48Z"
    mac: ENC[AES256_GCM,data:pUKXBwSQfjAEZ/pgezdLmmFJ16v5F9WCfuUTNtvMtoXxHDlr6CHFdezPGlekauMYvJTbdyLUxV4/WFzW+zgk40i+sjNARdokrfyOYJ8HGdQc8J/s2XLufnRUo1nFfmw55sAjsh/nxP3WwYrXGAglWFm4U6mTPggdQJTB55YuaV8=,iv:q/qT/kfZ3ydTGbS2HUEVit4u9BLoyS23hPyeKEvJEDU=,tag:cdMXCJ2H5JW/ZyaS+O5/zQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
