apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Vn40FDAjuqedgEj8sxCBOd7eZ4Y7NZ2sE/SHWvwgdH1Za+p02MhpjzKLh0o4QlCRZzjgkVBUUZAvBg2tQiZ/YRvoWbOxEgdykiRpet6AZUSZkx5JivnCUmhL2aSRC6gxghz631gy7aB35dN8zR9tWPfckXU6DzBaJKljyBtEYEDY4XJ08zMW7ouZOXeyPCY1wgT02lNrTc6bTWhuqjccvUY1k8anNMcQWInEk/4CNgcFNe9q4Se56I59p0M4K/UyNG3XZpw2uQLMauHnRawEY26m++JXZSIu+wQTHJGOvk8EQWpL5CYBWnvAv/pHgB6BWT1uwAex8iTPFFfN8ok82AVZ3PWUw452M1Hc+83kWKs4lozaKlqTmKG4NW8WUrY8,iv:SnJ785vAWeIL6MmkqaNsEyzXuN1v13hMJVvBzJdmwSc=,tag:jWHWXKnXruKZgT9UVDMxpA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NWXezP5/U2UbfhychOqWm3VMfyCK9par6bP7iHFfWNa1jIMWM5PGVovqcal0zprx3DNHnJjm0YATH9p3NSCsL7lMf3Z9dT2jWCGQ5LludjvZlUEDbN4FlO9kpqk+8Xt8oIHtBEeAD1BHrX/c5cCJQI6Px2NZrUnQvRvpC65s7cgajX133aeNgNPkFJOO8xVqlonAusRl8P/z8ZTVqrKkP0Lz+nVb9Xgr8aBedBXhs9+CPTAkfqgIerTIoaa0vxisHuX7FYmwiUUqGBzbog==,iv:Etxo8mPGVquxy31cdgGlAQQnW1MPzwK7Y1NIZ4UnvOI=,tag:QLiT6OOyz8iQp+V8SlRTKA==,type:str]
    known_hosts: ENC[AES256_GCM,data:WVfdr4rqmUVbikwp5urgz09jt5C3bJMlzNMjTCCS/63Vk9G3ZhQSU8eNm7XdAUTOazo+SE70OYAkDbsn9pEkLjqLTvYMbhW5u6eQ/nHclvorlVdM9ck/a8ao3M866o8eYV1OSZkW7U+Ok6g9NF75au+uWa0OGyyMlq4ZGNVupZXNnUVhNeN1U5sBbRW4/cdLxmFJvtYXO+xCLlIVfH1k7SkWcl7ha2RPCEQy,iv:sXzKEFJmJ1js1Ao5HMRCZXnf5f/JaO7HjoY6RVD/dkY=,tag:7QGNH0YhFoHVRkWhtg7wzg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U2ozYVJiZXJCRVJYS0Yv
            eEhVL2xVR3RpbHM0d25QVHJXZmFNR2diVlZvCjEvdVErY1JMQ2MvaGNmcXZMa1Vz
            bUd5RjBISTlrRVBkZVB2VDR1RDJGU1UKLS0tIEc3bEVCb3JYb3h4U2thRFQ3U2xF
            ZDVkbjNQQ0pMWmY1Y2Uya0IrL2Q3bHcKIs3RfY3sZTQwHaAMB1/b/qvqyDcfVgYI
            p2BRlnlFuIoPukxxQyqjwru/2lZMKVTaH+Em+HTMw2/ATrQXxgib/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T20:58:42Z"
    mac: ENC[AES256_GCM,data:9AKoB7+XDnz1sy080AiDR2ExKN/LLSYZ6l0dlhwWs9D4yVrjmm/lvZY2T5kIFEZ+/0dQ2tcCjuNBr1wF+olNEwjRN08XsxGiK4R7ZrGWd9/QLRvSQHoDGLKincq6BW9+7nA1Sq6cfbCI0OV1lSbcU16Fo/lw3iX0M1zG7MRP3i4=,iv:wVRvML9PDpeyBVzN0PYFhQQSPisuNqo00CzqwSr9y0A=,tag:uexUUJVli+AEnPg7IRdSEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
