# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4LWqc5L2ZiErbMjkJgxA/z58tbTZ6EEJRmiToH26Tnv2BTbmoRh8QKVDjt7WoLlcgA5WRbblhV4QScbmmENRvX9yuiKvHMqdSaB+XjQeFT3nHhpRf+wz4UwFTAM2RK9WwlaDVnO0a97r1L0e15/KLehHcNWJR5S1/2AffqQVxee5TmPobjmpn2rz2bvtUtKqVOJMda3OXgZ4XPIoCGjVUdFiwm3nMVOWyZpWzi9sdICJ5bf3iphKM/sLohoHorly+W1KtPBtBwLkrkSUS3DNdewfg9FHE7zJV7b/8U/x2uuy+rIm/uctSGS7sr6AmLzuJvRHtWiz+M3mK/46JBFMT9fed/a5dbJv3j03xbp6TNRe+F9oQqKyW8dj5gXj34q5,iv:q3i1SGb3vgrCirSqUTW9CxIq5zq6Qs9o4H53BBFoBUo=,tag:5X0sIRxjwreIHbr5B8ifQA==,type:str]
    identity.pub: ENC[AES256_GCM,data:L0hHr5OFEetFN870Q1sXcFdldjEv2JZCaxgRbUl7qJrtUCFmXAklG7xODSSQrHzWt7VfdIQuDQju/3+y1hG71gIyYSYW68dTZpsnffC7QyIodQ/wl/wgtASDqQD8g8TQA5/t8rgkWjG0KPTDtZLOh6xskPc2zDZCMLP7GYK3d+XNqy4UtcRgvAXTHRemNhnUfdvPziU7QEhifP4EYpXyaTy1VcJ6Uwkt2BouZ94mubkGOP6RmnFhiSgqgC1Y6fzhR6TItvfOCV+3+vildg==,iv:iIGTU4+jWKn0lzQofQQWtjfp0DKAsvcusK59OiM5hrc=,tag:DUBiGL45HL44GHOt0mOcaA==,type:str]
    known_hosts: ENC[AES256_GCM,data://s97fob63dL9H+JJfPM6SyVeQXzgKIvbm8LXTBrhnNwanCYtzx/Y01MH7nmY8X6GigntjiE7JKJIVUy6b+hnnLQWDqRvW5kOfWjW9Jd0RlBDZ8oAGwXwUI8HPPAcbe7eUK2ldanI7womnrsCRwWlZi9/xr1D8ntNd900xYy8SQDkYDJVZeaIHJJkHgRq815X+Eb+c7l94a54BT5PFHi+B27qBfXxTc/wNHE,iv:hJDr0LvJQBxFbdrOVEP4uC1Wv3dUNS3sXZTZDjMHQlQ=,tag:SE3vt0BDA3Hb1I+uMgCv4Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUTR5L2kzSy9zVWtwUk5k
            dnFzQ1ZaWmZIV01LMExPcWdRaUhtWGlCM3lRCit4bjI0SkRCRGE4R1pBUXU1Skpy
            S1ZyeHU0bFVZdUZ2WktSR2J3OTdQdHcKLS0tIGFDZWVIeTVXY3RRZ3RWYU5GZzlz
            cjBFS1VuaTBTYUF1clNGK0VSQjRUbEEKNMVSi8dLercIqaG6gvHnHrgyg0YrilSt
            0WkjoSYNQ6fhXygMbQai0aSCWU1h6rO2MEStaagJyL/uvbc3TJGPGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-14T16:36:59Z"
    mac: ENC[AES256_GCM,data:ya56SvKelfUFNvKE5WQPZlR3jHfR5PVyMMBDZ9/25BGt1KzHprUKO/GEIYqRXho6NiCvvmY3fYktpGy2T9IEsI48kO1i5dUi1x+2o+0FRD817PRsi9gTxvwSkdd9uHTlkh+SffzzjBbyzjF2t/r7kcE/tI31zGBJGYF8gKvZTdA=,iv:GcYGnw3ynapM0C8XQbHVeD+ZsURDxHMMFOHkSyugZlw=,tag:TjBjYuDAs1W0HzM1lxpoRw==,type:str]
    shamir_threshold: 3
    version: 3.13.3
