apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:wLYpubkBqw0bO2M1dskjTllD7Cq3pof5sLlM27TIUe03Cw4S6VJD9p2KnMeD1hhaDKRgrbSifw1mQz9r8KrimJvVqkWtQ/TKwC4=,iv:fx8VIqKvpMHKXv86RE+feIRDFhHMio5RWhob9pa4WjM=,tag:45cynntUcXYn9dF8kXEXeQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc2tJYU5pU3pSN1o2SWV3
        YzNwbVpZYWhqQWhFNWVWdjE3b2hFWk85UlFJClVLYXRmVFpNdjNyVmM4UC8vRXhK
        WS9JTEdYblJjQVUxRlpSSzFwZ1NZaU0KLS0tIEJqZlBiQmphaEovcTEwRTJUZWZM
        Z3RNcG40cmdxa3Z2MEwyNmlIOVB4Y2MKl9CjVI6jkfkXzq38SI1WqrydSYKZzp5P
        vzkEwXEB4uifQStQqoetfAhcno95sCT4UVcIVZWqbJN+E1ld0oTX9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T16:33:26Z"
  mac: ENC[AES256_GCM,data:FSdmn7YwnPbKEwc8mW+bjQAlS0BnCmC/c4j0oa/a5l8T2GZDXvk6CMZR5EYTcdo+iGwYyPxZqEMLmZteDyw4R63UKYhBcTCRsgypfaWBI7/B3WobiOL024iuxuLZvS52vId4DzZtj5Cg/Yb2XHwpKfp7uB6xGwzrm4AUqiv05vU=,iv:mUo7meY+dth297g7Adw5qUGPIzpkodLcw5SFyyA9zLM=,tag:zFxFgrn2xoc/QCiBkk1w3Q==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
