apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
stringData:
    age.agekey: ENC[AES256_GCM,data:mQV+ICxIDIHDXIHxKGelatQ93cm42q3RSx69Zua3uWqvdP3DOYLvQL2V5gu1TKUP3BhjHULv+ghxiqhjdreL8/YKe+TgTcv4XJg=,iv:senjwTZs9y8bEkLDMVT3oHQSNXwujDCTJxTNoQNbsns=,tag:j2uRNHYTzsGstY/6HycCwQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkam4vVGphcm5VbStHUEUz
            VllsSUJXc25CdDhkN21XTUdHOFdrYkIxeG00CjBHV2ZsS2tRcWxxSkxDMHJhZE9S
            cSt4TUpMK1R6ZXEzRXpRUWdrMWQvenMKLS0tIEdjOUZ2ZlRIcTVaRDN0elVweG5X
            UjdZVFVCVmFwUkNhSmJucUpBUThWM1kKjzM0h1AMK2aPffPjuQb9lPtEGRBydvpF
            oTqjEgIoSI/oJKUOV49aEvSropJ3Vs/GreYLWhlno1VoO1Pa7+0RvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:07:55Z"
    mac: ENC[AES256_GCM,data:mjAvTo8ffLGuNesVwL/GgX3+N+FaD342lOnkKfEhaUKkzV8cjXsyKsQMUN9hka0PJvjFIXvKFrcunpmWnakoABzJO7kheSqUHne6wYP/BHfPk+Sm0wMHSl1JTBrvs0mbp1+jVB/+mEGjI5zFOC6pFUv0gBsksmtl6KoRuwWSFD0=,iv:JJm/muLb6uZl4hUCxWgtC/1GyYqh/4aGgLzImGrDoiM=,tag:kvjTP+dxFk3xgCwCq3XRag==,type:str]
    shamir_threshold: 3
    version: 3.13.3
