apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:jc7zSx0tMOK5p6AtmU+f1o4bf4flWDzvWss+GMXmUvqWX2hu0dax4HwP4uSzNJNXi5CY0063BOS0VMrt5CA/405+jfiFdGPm2QU/MRAL0BgWmTqivpq3E2oq6wKH3jCnTR/nlsCE8mipzQeMGU7sqWmaV9IS64nfvjP0bQ==,iv:Wk2Q3dFYoEGtCoR06XIj4JltMkUtLmoOHM/D/N2M2NI=,tag:eeIxdrKzxlYOcQrMjLh0Ww==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:d+s0oax3pp2ut0Jx4YNvJdqhMtbbtDY5xGOO0OkmcCT25DYtZL1zFVuCcHi4c3QvQTuRlEO/VrexZAF8b9kotw==,iv:IyogUlqfwna1xrjuH1wUeh8giu83WA22lQNs3A3t9t4=,tag:lAsjYKotIAxYVpSeelBv5w==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:7JSMXuJxV4CqQWdS9D0/LOGohdCchDdjOpHYcZPqJfnCtfOdppQLnK+nF8LGfKyhG2OtQqfweVDv8RD99p2omTaDvjZLEkL40T+OL9pI8qi5nLCChDUqGNw=,iv:HD/gxp0O2o0QJSRy54uPkffSSnZV3tWVZVvZsnLaZSg=,tag:GIlHdahcQaQTJn+3LHsozA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVEhMeWJVVFlTOTVvcE9C
            a2lXYjRrcXcvRWlmSlIyQkdmemwrQU5XTmxJCnVlNFpTSnNYQTF3dlNPS2VqczZJ
            WDYyUXhISWp2eEE2ZVZvU3JnWWVCOWsKLS0tIG5wWUlISm9IK202eVRRRkRFaFY3
            cGdJZ0NaZDJMRW5IVG5ENmFnWGFES0EKkVgECP8Surm2ZXcN+pqauRLS2EJUv31C
            Z0nFQDun0aw0hBKiq8674BCH4TbWB1Llh3BtcCnvLY3WlVOiNpjJ6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T18:37:46Z"
    mac: ENC[AES256_GCM,data:4u9n4CFth2763kTLRBY1p0lpGSxvWQACiv0lvfkgD8JOGXDjrFNC0wQc1SlNEDc0K/4kMlm+h3XtX1m1p1sRqMIJocU7C3OPpa4Ky2r4ocy9iE1RBjArk9wSp28jQwkveeDBY+RrkltpiQ8ZnLym+3TR3p+jHVw/x/vnm0otNo4=,iv:zH8CRpIz5AI6foTvKhyC2hIJRe9CgHd1tewjDsestGE=,tag:+goRe4lL563hAwEAXAKEeA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
