apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:NjFZdsmmKXyjvgcsqbg1yTfCGrESB8Btljcu6EwE0bxCSdRMX98IpcnOLEa51VkbU0OHGIdOGwTG0Bs/oWdk3bPFHoUOrv2Q9VwtE/3e5iNtREzVm2vmex5Q99dHAU4VdgKM95t6utjInPLkONJtdDEEMmu/QPmybiSwiA==,iv:qs3ATqtZJxcBRq8H40wv1zZO4SQQVzXslZn8qBJvcYg=,tag:o5DcppM3/51gOz2YiySW+w==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:ICX1D6MUWETF8Ieib/eHOuWFpV/JvoepH0Wg64XXT9U/3neheXgXM57bIdXrzZ8ZttAvRZY4/UXojldzjIZy+Q==,iv:gjrwNZSzCLCLxtugMIO+G9C3e9nNIiVWfwCe2D/7BtM=,tag:mQHxQjj8H8jH5HP8Ai1ORQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:5yiLlqthZCyPrVz4P4g3BORrxX0q1PmGdXuEYIG25j/hYoF7mJGPG/JTeUC/c0sD3xNh+2atXSLELH1gjUj0s6T8I/zJCqIocnSB/hF9xyIh0yt7qFjeXBg=,iv:m0Z+zgUbDsqN4YVbiyMre0H3iB84rHbXyThZZVieFhU=,tag:KZSAbJJq5K54WAsPr7kozg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcDM0V2xkaTFzY21CVC80
            bHdsZVNXZHJtdCt4M1piTDdIR0hucmFWVDBvCml6c1dqV3QxRFl1aXk3cFIwcVNV
            SVJpUHFTaHRqcXZKazlRdnFIeEVxa0UKLS0tICtuRktUUTBieDREZFVLSkNtK3pK
            azliTHd5d1ZyVVFpb1Mxam5Yb2FQcE0KGtN/FT7LR7gEnDsnUAzaYV+XvkrGgbfk
            H431q7vpe1shKt+Z4ynGMGpoTfHLkKszVxVO2hh/N/UiMXdvMQFQpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T07:21:51Z"
    mac: ENC[AES256_GCM,data:+AUTjpZkkX4bGni/H1Elfj6dBm8svbdxKd8T5WWIywlSRqh6A8mucbRnrBAywboy9Jvh5hFEOR7fcwaYUZPnk9C1DGzq4/og5btcUiBbxim4vlKNRQ7B92xuY+fapP21fZht7nWojucdxwt4uPvTDV1zga+/DZKv7iLm85u0BP8=,iv:AOg0xO9YiOYNXhE3BmpocCsbxW5Fg3f7a1jarWrmrwI=,tag:O4gLRd2ifhpffZOHNPJVKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
