apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:R2mK8JTKjbfum71DRtkP05AGxpcDoZQq7RCGIqnQ+ccYrPHBq8b2RS+jjVxyPh3QKnv/nXtmuwlE43DWAk6LXkUU2eCdrvsADgi0Je5pxC2OXLD/hVLOjI9HTv9Z0SgeypMOZLZEIHtzUkWPGibGZdU9aIakOfmQbJ648A==,iv:NLxNQ+l+UKt+fEtI6IHWRs8+v0Alz81yw3F0AMr0mUM=,tag:nmE7SrOZMNFBtAbNWuABXQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:0P3ZxQn49HptiAQNcO1hI1iBJ0S2x2Qbu7cH1tInZZaqtmOLk/vtVcpv9m73fLGhcYvVXQBWJ5JO2Q6XBoRG8w==,iv:OEsySziUog+x29+lNta9czgN1uf9+ZaUvHs1XxbWLBI=,tag:YwHu9uOhL4Ve6LqOmoYB4Q==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:fVE0iNNl8jdIsxaTGfSyLM+6BfhxvRjE0/H9tLyuSVyaQ+Ir5WE1I+zusxUCyiCcXFXwJ1x1Ej1F3ocapGKXTvnpInvX9kFYYc/f0/SSW/X1XgqNgvL0thk=,iv:y28nXqAYNDjHAiwvWbMyPBvcC6QzlMIq8CDMugYUmpU=,tag:mEdXahVEXvIWIl0lrj89Mg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL2VBQjcra3IzTTlrT1lU
            U1NCeDZKWWozSjBhZmg4bnk4b2F3ajQ0a1ZVCjl3L3VlNCtHT0hVSTRVN2g4SEFG
            UWFUNWZUL2w2cll5cHhIb3JOTHplZkUKLS0tIGhhek1EZmZMdkNzZ0pEc05ibmIx
            VU1raWdtUGg4WUZoSHY5OUxqeVY5OWcKF56H9H/SgGEGEBmKMvN0w0ryDVoxuoSF
            LyjxPrQNzhplZ7wOWfL9SFp/s/pPAkjXOKrehhFRtCpTh1li7AH4fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T17:12:45Z"
    mac: ENC[AES256_GCM,data:Y0T3TdBdtqrJg4ehZicN/l0YMMKUz7Ove0TZAxUOKYlRgAcIKCVu46vzZHWAQnFmSqxJyv8a4zQ/BteYAXgqrT6vuXPL5uBT7zojfdufT6lhx93aGMHa/wCXCMJqef3oxQM7VqCU+ZMO2GeA6N0TPyfpTzJ7VgVe5woa9Civ3Ic=,iv:gUfYmudcf1a3h6eFLW/5BtJsjOV7iKpjI/6B1FiShCU=,tag:VkeC+uUTvNgN2wvZ0g+GTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
