# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: credentials
    namespace: grafana-operator
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:ar+Avg==,iv:6vZxle9WVQl87bijL/G4H7HydV2kaoIk4IZFQSAJfCY=,tag:Fef4KFM7qA9J1EAmhoKZEA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Z+I6+/vmmUzv2Q==,iv:tKFsRSosmjM9OE3D+kOqngtCC7Z7GbJoz0XnBSpfKxY=,tag:Pe03eyLE3SIcVmvkBJ645w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb3VqbXkvUWszR0x4WjBs
            cDl6Ymw2eGxtUDRlVG0vZVVjS3FZRDZBWjFNCkFiYmwzMCtvSXEyWFlFM2puZDJC
            dGQ1cEllK1dXa2szeDhRWWh0dTBRTXcKLS0tIFhySFRkOHgrcTlsN3JMbWwyYXdp
            Q0VYNlZPbm9xZENNcEJxQmdVRWFhVmsKXyfkr3aoPz++Q5k42WZS8V/uDOX7vEzF
            wGxFTb0fCc9w3kwb1cNQVUVzkQa41EqfMKM3sw9T/NRAF4IUoUdvSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-12T11:10:21Z"
    mac: ENC[AES256_GCM,data:C6h8lqGoDjjwVs8cPEBFaP8C5NFSN7D6ML3NxsuyLA17IncP/cLTneYqeWGK+Mbx1tzt85EdK+sXFxg017iCrt5IVgcIFm4ypMU/p2N4b1CcDSr+GNl8HHvJM31bWkBA1SN7qaklhJl3CqTmtejzJ7V95NR1Ql4KidVsLxyIrrc=,iv:niQHgSyxXjfzQ5Xo3DA78PTWYWEKPrwTAcbnMn1m/T0=,tag:NrtQkqZ+BbuXsYvKa6fnBg==,type:str]
    shamir_threshold: 3
    version: 3.13.3
