apiVersion: v1
kind: Secret
metadata:
    name: credentials
    namespace: grafana-operator
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:hfdfNQ==,iv:BK0yqDRy1HtMmk+30p9Qln2DO5yAEJ7zQIvyhVek0Ew=,tag:aPys2YFgkjyDQ1BYT36rlQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:NSTesNTQdbRV3A==,iv:8qVKFnCzummbYIqbP8QayU5ty39Xqywl7M2TEbHjgtE=,tag:eklZ1IF4RIxBB4tRw8ntpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3KzlZbkdhcTMwZi94NjJK
            RUpqNTV4dngwZHN5NFpxcG01RVE5dzIzd1hVCmhIV3FBRUtkWnZnTDEyL3lxTUhP
            a3lkQlo2RUlrdElIRE5iTGVqTGxFQ2MKLS0tIEZyejRHUENTS3FjNHFnZUZNdlRt
            ZXBsaGdBSkJXMklPbGFaV0JsRTRjWVEKGLJStfJHxhW8akLGO11ZcXMl0tiSvDUp
            XmdCJ3P30YRBsZgwnBwmkhKsN1CXSVHrHOBgkCu/lcnbhk4xHxPy2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-12T15:56:21Z"
    mac: ENC[AES256_GCM,data:rkm6Ka6zYGyGD3XxSxg6gGQXwxZOKTECnU24IeojX91grxtm5yHFYEMyyzGZbyep5cyHUEsdD8CRJmsqssh7a59/qHhqcewDw1c1VhQBpuJEq4h0hVBtizxGALeuUZmnRQnUBlwzwGX0xHrXqU2nifAdOrvQHnnvDiOvytHftQc=,iv:kwdfcu6Tb0cRGlhZigVKIpvVzC1fGkoHv0dJIosvQs8=,tag:oFf7nCrsl7m1CxDn5J5Ivw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
