# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: credentials
    namespace: grafana-operator
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:vYjUgw==,iv:JaXzzTK0uQFJeaR67SUjwbdenWGkVpr7QP2pdXsmTFI=,tag:4cn7ghok+qVTnyoK5GqCOg==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:1xp+lflz48Dt5w==,iv:0K64gpFPeUoEgcYtVIFolkyoqLt0lD32mNS9OhNuBMs=,tag:D/vHfT72nJqYMQr4BU/DYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeGl0RkxBNXhMWDE1ZW1X
            dTkyVkZ2YmRhYVdQQTcydjFtOGFkSjJIMlJnCnNDT2R5NWpGYnZxU0xUWjB4TmIr
            bFViSTZNOE56OEhiZEorZmFpNnZoRmsKLS0tIEU4cjZLMlVkbGhWZm5uTU1WU1A2
            UXljTCswOWlUdDJ4cDExcWR1VUp1MWMKFGmabfLWjqwc4YvelEl3SKSw4bYbqMhz
            1TfzOFWnRFjAy0M1JSpiTIIHi3jU6H/3oxEtVan/CNyrn3Kk0Zd0rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-12T11:39:28Z"
    mac: ENC[AES256_GCM,data:e5mDNJdXy9WwlOxTSIiFYoM1tOiU88h+bjFJ6UdLYbRtALLYPVzd4W8tAd40nM74YBPb81GYgHACWuqS9dtyOZ8RzA1OyhLD1TPE+OF8H70Xj8OHYJRop1PEcdI/NjEZtKqfX95Q/aEpT74n/GRTwmC4vEVRO0oE3Ym+jRDmrEo=,iv:XcZyWg17P60rufTOydFq6NWEwnc6e8SK41/NGlrYR24=,tag:g59bE8ja9PnXKYrsBqbdNw==,type:str]
    shamir_threshold: 3
    version: 3.13.3
