---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-stats
  namespace: minecraft-stats
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 17.0.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/xstar97/mc-stats
      pullPolicy: IfNotPresent
      tag: 3.3.1@sha256:8f366c1ec156b730ebfd7668f19f5fcb8156fc9eb590ea15277beaf838907638

    TZ: Europe/Amsterdam

    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsUser: 0

    service:
      main:
        ports:
          main:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: mcstats.${DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: cloudflare
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN}"

    mcstats:
      utopia:
        server:
          sources:
            - path: /data/utopia
              worldName: Utopia
        data:
          documentRoot: /config/utopia/public
          eventsDir: /config/utopia/events
          statsDir: /config/utopia/stats
        crown:
          gold: 4
          silver: 2
          bronze: 1
        client:
          defaultLanguage: en
          playersPerPage: 100
          playerCacheUUIDPrefix: 2
          serverName: null
          showLastOnline: true
        players:
          inactiveDays: 365
          updateInactive: false
          profileUpdateInterval: 3
          minPlaytime: 60
          excludeBanned: true
          excludeOps: false
          excludeUUIDs: []
    workload:
      main:
        podSpec:
          initContainers:
            update-config:
              enabled: true
              type: init
              imageSelector: "image"
              command:
                - /bin/sh
                - -c
              args:
                - |
                  set -e
                  {{- range $name, $cfg := $.Values.mcstats }}
                  
                  # Create instance dirs
                  mkdir -p /config/{{ $name }}/
                  
                  # Write config.json
                  cat <<EOF > /config/{{ $name }}/config.json
                  {{ $cfg | toJson }}
                  EOF
                  echo "Created /config/{{ $name }}/config.json"
                  {{- end }}
          containers:
            main:
              env:
                PORT: "{{ .Values.service.main.ports.main.port }}"
                INSTANCES: '{{ keys .Values.mcstats | sortAlpha | join "," }}'
                INTERVAL_SECONDS: 300
                
    persistence:
      config:
        enabled: true
        targetSelector:
          main:
            main:
              mountPath: /config
            update-config:
              mountPath: /config

      mc-java-data:
        enabled: true
        type: nfs
        path: /mnt/SSD_Cluster/app_minecraft_data
        server: 192.168.1.50
        mountPath: /data/utopia
        readOnly: true
