# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-config
    namespace: flux-system
stringData:
    test1: ENC[AES256_GCM,data:9udzrfsXjtsNd2R/rcEGca3mRQ==,iv:01GSlwGKblDBkUz4piBeQ7LmrGC6J35nWQyKsF+pl/E=,tag:26TDMl+P1qbz5FMooKnU4w==,type:str]
    ver2: ENC[AES256_GCM,data:/m3PM/K4y7OwjPSnTyl3a5qq,iv:zvMOSI3RIrAK9i5YjfTmm0A+gh6lbsxZFsiO842PXUI=,tag:7dAAo1SOtSDnmnFHdML7WQ==,type:str]
    slaap: ENC[AES256_GCM,data:lepoXIohTQS4DiBpuA==,iv:uJLG/jRISh9uiu4Ppz6m/GWuZCg09iAF2d0TO2bwLDg=,tag:fseRG2RvVhzcUnWjfme/wA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV1JUSHdXWWRSbXY0eE9j
            cEZET1lndzIzb3VENnU5MWZOYUg3dGlnN0ZRCmpOUFpjbzFmcUFSVWFuQm51bDI0
            bTB3dDBDeHBEcXpGcVFJWm5EdUh6UGMKLS0tIFJncnB2Zi9kTm9XN1BGNUxvVUM2
            dnFMaTVPZjJ4SXR2VkZaYlZvYWdHalkKuKA+CfxIJ4jwzkQiaYvMZ4ouWxOJKdFM
            vvF/YY8eq5CKHKfrX+Nafkt+bCUf+hbIqce5QWrpPQrH2M3fZHzTWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-15T20:00:45Z"
    mac: ENC[AES256_GCM,data:1Qp52FcFDSimDj4yJQXeD74lsMz0/+RaeFRaB1LXYZl/xErD23ck2q5Skxm86N2Dk/mCK4uhOXdxM6OsX73pfPC1uV2TEcBVpuFKXkIhqgJIj/p+elH5+uz3BFETcFMJlTXvQlEvymRL6KKz85OGimtCqd1G+1qoOTrnJOTwyeY=,iv:E87mp5AxoN/tvLYnzCCus9K9Mp4CbCcm5YBvj+M7+zM=,tag:A+Ir2NyDFZIYvVWPODnlTQ==,type:str]
    shamir_threshold: 3
    version: 3.13.3
