# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-config
    namespace: flux-system
stringData:
    test1: ENC[AES256_GCM,data:FfwFUQZxItlk0B5mW/1qwM9WNQ==,iv:zrEQQsPXN0nTHKaGzJIyFsW3NNPzCC3k0ayEYygybhc=,tag:UGIxjoaqKEmdh1wQHxTO7w==,type:str]
    ver2: ENC[AES256_GCM,data:fXe3f9vZ2amfkqPMHFPhvKgM,iv:zseF0TT7czMeDoNmGQp9QZQMRLD3BaQ0tmhz8wkvhMs=,tag:W04UFRj1m8+lVwK871X4fg==,type:str]
    slaap: ENC[AES256_GCM,data:ATraXI17iUeUz580eQ==,iv:6XVI6w3Nphetg0CPCkL23zUsfIOBln2iCcD3nFWl5Po=,tag:F/iRwuchIUscGTEkcc2AOg==,type:str]
    erff: ENC[AES256_GCM,data:ExQhpU1KyK5sr1Uahuma1gJE,iv:vbXaXv+pbUafG9xbbZZwRxRmBNzepVei+YwcsVJYKXU=,tag:vfV3QPVhvJbs64ZLJuaGYg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSVBnZ2JVV1poNElYNVlT
            Z3pwWUI5blh4ME1wNHo0czcwc0NCU0g2QkRjCitjVkxNNWxRbVkyMzVsWXFLaWNL
            MHREcDVKVmZrU2h5QnUwajJsNXJSbWcKLS0tIEQyM3N1TVRMcGtNblpGZDVQdk1M
            UTFscjNlcWRHdnlxUDJBdFA2TVkycjAKT3BaZDC5ZFNzXODPHVRBJXFipkEHFUOF
            m/Qt1LtjOrBUpZTre2McoiAzRc4iRCx4vvAkpAfrKpxg7aWWD25PSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T18:56:56Z"
    mac: ENC[AES256_GCM,data:ut0rfdAgUKYBcBJnNAsIqsh0PT+w3XDwDc+mq7x8H6Oh1T5UQe2w0YNOPbZn+RbBy4uDTqI3Ag8G0x+md2qYjb4vyWork9qdUT3uH4DQixfCMXoZjDGfcfxNP7+nePi5c6e4RfoSSw1dzkL0g4R4aAL7wX5XM26LAtGMpkvujpA=,iv:pBOji3JIQivG9Xo7raeMff1jldKjpx0g8+P34mJxi54=,tag:EagbBaE+fxSx3QFng0qTNQ==,type:str]
    shamir_threshold: 3
    version: 3.13.3
