apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:qZbRbT19C4tSjHbfKMUdSGkCknsOdUhVTC1CMcAtMSESNIgGz6iw9h6SgnzQXgm5T2VtKIPCEwV5PKSZm/VtWD15bOuPihl6su0BtFnK/ooeCPojsF1Dd8VMO+InPFtcLlwYLSYEpRxMXmAS1ZpW1NEf5DEYsnwJ+RdHIQ==,iv:6t47eJb//FaJzPOOkZRsarzhkqdL0D8zUcmvLIMXJbw=,tag:9NIfAi0vI/ato953EFz3ww==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:2IAgi9hxtHyrC0qw7GsxQbiGG9AYCaQ3fFPtZ5wF3osMB66ldAjycbRwaunHczH5xbdeNlxJ4CaaI/XJCdng1Q==,iv:Yt7m+fj2htNye+VLrLRFIfql6VNfqXgxuSsbZu4H0jo=,tag:jPEYYYOYDMxvisfeEu0wjA==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:D7xyfXMrdbd7me0FfyX/spdOFWH+RYDiw51AaixnghmeC4wGHbfmsFpWYpYVVGPjc3+VvIkg+R0RO8dJMmzz02ilj0Hbg6CoXxUocoSCccjm/u7htQ7xCRM=,iv:CzXMv2PbwUhnFdrFjbBX0DDoGUyglQgVelBJGpRWtiU=,tag:qYLXNeRzw7jcbP8oB8DKJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZk9zV3AzN3ZoK0ZqYnc5
            SmJ3NnJrbUJvZFpVcTlGOVFVQnhZWkVidW1rCjZtb2tIZEtzWExnZXFYSzQxSXNH
            Tlc3YWl1cEZBOUpyYVUwMnpOckZOSk0KLS0tIE5QWWx1SHROMW50cUhKdWhLSTlC
            MkNoSExUWjQzckhSblNKU1Q5SEc1NmsK8v024nCPbgZ49UuBcIt1LuOAW/+NOSic
            zL831ayyHvhWyRZ5R3m0Yyf96A9PTgYlpkyQiSaYds4KVUdkZE/Z7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-11T12:23:54Z"
    mac: ENC[AES256_GCM,data:BiijFDDKLb1WRfLvwE0DeSGwQnpsG/wWpFSo9z6tfbvi/rZMY/o2/E4NTu2q6ZnL8Aagc+F/QI71bnprebol8FjeiWWDBEhT1sKderU//SBZpiMuxyjAchTQwufnT0Ts9c94d3k9aDefe8AhUfGdXePRqY9vm9+rfF//kQMDTyA=,iv:yEMlZEkOKYBtrr1RTCYi4s8dfEVaOgOG7oMJlv/GtWo=,tag:nSy2LhYgxWHRIuS+Ce+kSA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
