apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:3XrHAehqR5ERqX1qGoz+EAuXqB1Cz4YUSr2eiZEx5Fax09FrJni4HxHD03/JyHJ/B9nCBn5DQQgs6M89RpLFqpcnNVQ/xd3RtooMBFmhObDh0EeCglZ6DmZudQSEUHLv2g+HKpHwprvqCJQs2kPsvLjV1pRmebi+xto2lw==,iv:zqzSTb5RL9gMXs6e7Vo5Og2DgAtRX4h2cLIQWE+fv9M=,tag:oCgkDiREjteZyEGIVOFhSA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:8aeGIyc0uoj2y0ZszJCkWMW2r0EJROZK1LWtyTm9m0G/Wa1dVUhuZgfNxdqaRjs3ZQCISVWxm0dBW2IpT+AMHw==,iv:E1FRrLxr5f4AIfgF4gBH3PP8rR3iAPuLQerDJfcvHvs=,tag:WwRQMS48U8kTSkPfrUiW4w==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:Ng+x91DhcLxfEc7n7DlHv8XYNOH57PQ2FYrejvDggQfu34kXdnEPaAj6s/ddD9ScIsq6n0njJHK764bv7ruRhBWwhBWKFAJegynv4BoKlqXRCZCtrHCzVCU=,iv:Adqn8VZZugl6jE3QVGHJEEqTtXiAMSj5cHjAJ0m4BQI=,tag:RXWVGkE4LQ6AqrWtMaQzKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMlQxQitldXQzZ3pYUlRt
            WE42bFV5UVBnMU1nWHl3STZ5UTRqNGtCQmxZCllpL3U4YTFFU1ljT0JzUTJJSHBs
            SzNvUjNGSGZrMzZxRDdGTmx4bENIU28KLS0tIGg1bjFreFVORU8vZFJkc2FJM3dB
            Y1J2MG9vcTgybEVCNDdoVHZ3UzNGUWsKz8PO3SW1mAWTbAg+H8Ap5Sb0fJxnZQxv
            BJfusocEDn4cbty/p+Acz/+bQnDcJvxQ+vTa01lxh8QySPUvqHLDsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-19T00:44:33Z"
    mac: ENC[AES256_GCM,data:G+Rc6cMBP5VnPMzLnAfyNQOpi41XbB+7rVmVtK3qCrMbcWWab4wcV3Ay83/8wD2dT7+QuH/2fQV7JQJLe8kR6W3KwZ8Qw6Jv1S+pzNq53+GUDhrbRAGyYfE6Q7mcrBxk9m56x1vGXuJeOzDeKRC/iGWLMlwxzDvKKdObfVezNZ0=,iv:ifQCoLYgGf75msNGgfgadt6evU7cpzXMIHexey1KTfo=,tag:o7/GntvJKYSOKJjN1NWdWg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
