# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:bUUF3LyPZxcLkAmP462p0S3hR37QqbV/90vswMyTLYOfO//pWZZHjMCR6o+rRF+PN4zPMuCgQPGpyTHJ68MKOF1kCnKe1G/pYa1/GGD2Qcetth06nFX2AR6oDtJSWGU6sBG5WR60G+rjknB6LOyWvdRrVY7QBdmAIGADdA==,iv:ZJ6NwFP2lE0MShwoz5tRAF2vuKoEY2YgNma69WcG90Y=,tag:Q4ZJatj5nGkyaSmwwZtEWA==,type:str]
    GATUS_BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:bC+QFGdvxI6y1Nbm+qwzPMuAz9kVaH2nsQaNJN2SqZmepleogs8N8HteH43++3UJFp12nFGeRWSAaOlPD4swwA==,iv:YCxkxEviXnDnGrHDQZNXjDuifQRs0sOl5OXFUxX6OL0=,tag:Z+T9qaSKt4SJ2vXdsBCwYQ==,type:str]
    GATUS_BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:cQnHUUTrQhHiPkPqgt+Mbm8LkzSUnYubG8cRukSshmYOcA4GWgrMalEjLkC0jRwxEj2st5ZIQ11/w3U1PDCGQT2R+UsnUYNkH92xt8Ek5HFs8KgDYpRBc40=,iv:xZZOQBtVdQr+hNrFql6YjN1mjRnDjdnborRha8V/xds=,tag:zKxaPJXKIbncAbWm1e9Lhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZG9TNCtHNWpmckRmOTRw
            L0tIcE1ocnM0OUdMYTc3cjlYT3g2UXZWS3g0Ck82Z2xxWHNNZEprQVZscXJOVkVh
            V2xOcU1GaitvZzdCcGtjYkxxYlh2NG8KLS0tIDY4MVhLR1lkdC9PbUpzRmJrZ25z
            WUdsWC9NRDVjb0JJd21mMmNXRFBiL0kKpIa8LzLeJbE9ZIM/fuxwyCR9LBYAIMS4
            +3FYc3FEPS3gZaV03HiXBBhHytIGVaBQ5BFLtfNtOKfWviJSDgRxyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8xty9t8mzeekkgs0pc9uezeu4lm3cdssq68gn0mtxyc9wmn6vhq3m2ych
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-12T11:39:28Z"
    mac: ENC[AES256_GCM,data:tRwQUDB8svmcPhHPUqa+tX6BJjCqgTleh/vP7CDSBGBACsfuyh/k1uPwYpbvXphgRgsuPa4poHzr87xiUc2mHQixDyASW/AsKilY6OOhTykkwSsYHifwV2cRdzW/IbpSfUG08p5ik0cWMo+vKrFtam4tjrjyQM62160wcY3uuwk=,iv:5oI2ydRSP8tcXiMVeTFtVh6/6r1F6Wl9J2EqzBdzLgs=,tag:PYJgNPp93ycpO9kpvhse0w==,type:str]
    shamir_threshold: 3
    version: 3.13.3
