apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/notifications/discord
resources:
  - namespace.yaml
  - alertmanagerconfig.yaml
  - alertmanager.secret.yaml
  - helm-release.yaml
  - scrapeconfig.yaml
  - promethuesrule.yaml
  - grafanadashboard.yaml