---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 22.7.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 80m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    global:
      stopAll: false

    plex:
      # User Defined
      serverIP: "${IP_PLEX}"
      additionalAdvertiseURL: "" # https://${IP_PLEX}:32400, https://${DOMAIN}:443, https://${DOMAIN}:32400   <-- configured automaticly
      disableGDM: true
      requireHTTPS: true # First Deploy set to false, till remote acces is configured and working

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${IP_PLEX}
        integrations:
          metallb:
            enabled: true

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hosts:
          - host: plex.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: cloudflare
          homepage:
            enabled: true
            group: "Media"
            widget:
              custom:
                key: "${HP_API_PLEX}"

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: blaze
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true
      videos:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: /mnt/HDD_Cluster/Videos
        mountPath: /data/videos
      muziek:
        enabled: true
        type: nfs
        server: 192.168.1.50
        path: /mnt/HDD_Cluster/Muziek
        mountPath: /data/muziek
