---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 22.11.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Amsterdam

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: prowlarr.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: cloudflare
          homepage:
            enabled: true
            group: "Arr"
            weight: 3
            widget:
              custom:
                key: "${HP_API_PROWLARR}"

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: rustfs
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true

    resources:
      requests:
        cpu: 10m

    configmap:
      dashboard:
        enabled: false