---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ext-denon/ks.yaml
  - ext-plugwise/ks.yaml
  - ext-truenas/ks.yaml
  - ext-unifi/ks.yaml
components:
  - ../../components/notifications/discord