---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-runner
  namespace: actions-runner-system
spec:
  interval: 15m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-system
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    githubConfigUrl: https://github.com/Boemeltrein/TalosCluster
    githubConfigSecret: test-runner-secret
    minRunners: 1
    maxRunners: 10

    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    
    containerMode:
      type: dind
      # type: kubernetes
      # kubernetesModeWorkVolumeClaim:
      #   accessModes: 
      #     - ReadWriteOnce
      #   storageClassName: "openebs-hostpath"
      #   resources:
      #     requests:
      #       storage: 5Gi

    template:
      spec:
        automountServiceAccountToken: false
        containers:
          - name: runner
            image:  ghcr.io/home-operations/actions-runner:2.334.0@sha256:95d91d7f8d241e319ef2f4fec08f417aa1606b96fbb327643f75c303acd30002
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
              - name: NODE
        #         valueFrom:
        #           fieldRef:
        #             fieldPath: status.hostIP
        #     volumeMounts:
        #       - mountPath: /var/run/secrets/talos.dev
        #         name: talos
        #         readOnly: true
        # serviceAccountName: test-runner            
        # volumes:
        #   - name: talos
        #     secret:
        #       secretName: test-runner